export default [
  { title: 'AI' },
  { title: 'Biotech' },
  { title: 'Clean Technology' },
  { title: 'Community' },
  { title: 'Construction' },
  { title: 'Consumer Products' },
  { title: 'Crypto' },
  { title: 'Cyber Security' },
  { title: 'Deep Tech' },
  { title: 'Ecommerce' },
  { title: 'EdTech' },
  { title: 'Energy' },
  { title: 'Entertainment' },
  { title: 'Fintech' },
  { title: 'Food' },
  { title: 'Fund' },
  { title: 'Gaming' },
  { title: 'Human Resources' },
  { title: 'Healthcare' },
  { title: 'Internet of Things' },
  { title: 'Logistics' },
  { title: 'Manufacturing' },
  { title: 'Marketing' },
  { title: 'Media' },
  { title: 'Music' },
  { title: 'Real Estate' },
  { title: 'Recruiting' },
  { title: 'Retail' },
  { title: 'SaaS' },
  { title: 'SPAC' },
  { title: 'Space' },
  { title: 'Sports' },
  { title: 'Technology' },
  { title: 'Telecom' },
  { title: 'Travel' },
];
