import { Theme } from '@material-ui/core';
import { phone } from '../../../utils/helpers';

const styles: any = (theme: Theme) => ({
  avatarBackground: {
    width: '48px',
    height: '48px',
    background: theme.colors.primary[50],
    borderRadius: '24px',
    padding: '12px',
  },
  backButton: {
    paddingLeft: '12.5%',
    paddingBottom: '24px',
    color: theme.colors.gray[500],
    fontWeight: 500,
    cursor: 'pointer',
  },
  backdrop: {
    background: 'rgba(112, 112, 112, 0.5)',
  },
  boardBox: {
    height: '160px',
    width: '100%',
    background: theme.colors.white[100],
    borderRadius: '8px',
    marginBottom: '8px',
    padding: '16px 24px',
  },
  boardBoxMainText: {
    fontSize: '12px',
    fontWeight: 400,
    color: theme.colors.black[50],
    margin: 0,
    marginBottom: '4px',
    lineHeight: '16px',
  },
  boardBoxText: {
    fontSize: '12px',
    fontWeight: 400,
    color: theme.colors.gray[500],
    margin: 0,
    marginBottom: '4px',
    lineHeight: '16px',
  },
  boardBoxTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: theme.colors.gray[500],
    margin: 0,
    marginBottom: '4px',
    lineHeight: '16px',
  },
  boardContainer: {
    overflowX: 'scroll',
    paddingTop: '8px',
  },
  boxTitle: {
    fontWeight: 500,
    fontSize: '16px',
    color: theme.colors.gray[500],
  },
  boxValue: {
    fontWeight: 700,
    fontSize: '20px',
    color: theme.colors.black[50],
  },
  cellValue: {
    margin: '0',
    fontSize: '12px',
    fontWeight: 400,
  },
  completedTaskListItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: '3.5vh 5.5vw',
    width: '100%',
    margin: '10px 0px',
    backgroundColor: theme.colors.white[100],
    borderRadius: '8px',
  },
  completedTaskCheckImageContainer: {
    marginRight: '15px',
  },
  completedTaskText: {
    marginRight: '15px',
    fontFamily: 'roboto',
    fontSize: '18px',
    color: theme.colors.gray[400],
  },
  completedTaskToggle: {
    color: theme.colors.gray[900],
    fontWeight: '500',
    cursor: 'pointer',
  },
  closeModal: {
    color: theme.colors.white[100],
    cursor: 'pointer',
  },
  containedButton: {
    background: theme.colors.primary[500],
    color: theme.colors.white[100],
    borderRadius: '8px',
    padding: '6px 16px',
    fontSize: '12px',
  },
  copyLink: {
    width: '100%',
    height: '48px',
    fontWeight: 500,
    fontSize: '16px',
    color: theme.colors.gray[500],
    textTransform: 'none',
    padding: '12px',
    marginTop: '8px',
    '&:hover, &:focus': {
      color: theme.colors.gray[700],
      background: theme.colors.white[100],
      outline: 'none',
    },
    '&:active': {
      color: theme.colors.gray[900],
      background: theme.colors.white[100],
    },
  },
  emailsContainer: {
    marginTop: '16px',
    width: '100%',
    display: 'flex',
    flexWrap: 'wrap',
    maxHeight: '200px',
    overflowY: 'scroll',
  },
  emailsInput: {
    width: '100%',
    position: 'relative',
  },
  emailTag: {
    height: '32px',
    background: theme.colors.primary[50],
    borderRadius: '16px',
    color: theme.colors.primary[700],
    padding: '8px 12px',
    display: 'flex',
    alignItems: 'center',
    marginRight: '8px',
    marginBottom: '16px',
  },
  emailTagText: {
    fontSize: '12px',
    fontWeight: 500,
    color: theme.colors.primary[700],
  },
  emailTagCancel: {
    color: theme.colors.primary[700],
    fontSize: '14px',
    marginLeft: '8px',
    cursor: 'pointer',
  },
  error: {
    color: theme.colors.error[500],
    width: '100%',
    fontSize: '12px',
    margin: '0',
    marginTop: '0.5em',
    paddingLeft: '6px',
  },
  headerLabel: {
    fontSize: '12px',
    fontWeight: 700,
    color: theme.colors.black[50],
    marginBottom: '16px',
  },
  input: {
    color: theme.colors.black[50],
    '&::placeholder': {
      color: theme.colors.gray[400],
      fontSize: '14px',
      opacity: 1,
      fontWeight: 'normal',
    },
  },
  inputRoot: {
    borderRadius: '8px',
    background: theme.colors.white[100],
    color: theme.colors.gray[500],
  },
  inviteButton: {
    width: '88px',
    height: '48px',
    background: theme.colors.primary[500],
    borderRadius: '8px',
    color: theme.colors.white[100],
    textTransform: 'none',
    fontSize: '16px',
    fontWeight: 500,
    '&:hover': {
      background: theme.colors.primary[700],
    },
    '&:active': {
      background: theme.colors.primary[800],
    },
  },
  inviteButtonDisabled: {
    width: '88px',
    height: '48px',
    background: theme.colors.gray[300],
    borderRadius: '8px',
    color: theme.colors.gray[500],
    textTransform: 'none',
    fontSize: '16px',
    fontWeight: 500,
  },
  inviteButtonContainer: {
    display: 'flex',
    justifyContent: 'flex-end',
  },
  largeBox: {
    height: '500px',
    width: '100%',
    borderRadius: '8px',
    boxShadow: 'none !important',
  },
  linkText: {
    width: '50%',
    fontSize: '14px',
    marginLeft: '15px',
    [theme.breakpoints.down(phone)]: {
      overflowWrap: 'anywhere',
      width: '70%',
    },
  },
  modal: {
    width: '520px',
    maxHeight: '672px',
    height: 'auto',
    minHeight: '432px',
    filter: 'drop-shadow(0px 20px 56px rgba(0, 0, 0, 0.29))',
    borderRadius: '8px',
  },
  modalContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContentContainer: {
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  modalListItem: {
    display: 'flex',
    fill: theme.colors.black[100],
    alignItems: 'center',
    '&:hover, &:focus, &active': {
      background: theme.colors.primary[50],
      color: theme.colors.primary[500],
      '& svg': {
        fill: theme.colors.primary[500],
      },
    },
  },
  modalSubtitle: {
    fontSize: '20px',
    fontWeight: 500,
    color: theme.colors.black[50],
    lineHeight: '24px',
    margin: '16px 0 40px 0',
  },
  modalSVG: {
    fill: theme.colors.black[50],
    width: '15px',
    margin: '10px',
  },
  modalTitle: {
    fontSize: '24px',
    fontWeight: 500,
    color: theme.colors.white[100],
  },
  modalTitleContainer: {
    height: '64px',
    background: theme.colors.primary[500],
    padding: '16px 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  outlinedButton: {
    border: `1px solid ${theme.colors.gray[300]}`,
    borderRadius: '8px',
    color: theme.colors.gray[500],
    padding: '6px 16px',
    fontSize: '12px',
  },
  pageIcons: {
    display: 'flex',
    width: '50%',
    justifyContent: 'space-evenly',
  },
  pageTitle: {
    fontSize: '40px',
    fontWeight: 'bold',
    marginBottom: '32px',
  },
  personAdd: {
    fontSize: '22px',
    color: theme.colors.primary[500],
  },
  placeholderItem: {
    boxShadow: 'none !important',
    position: 'relative',
    background: 'rgb(229 229 229 / 50%)',
    overflow: 'hidden',
    '&::before': {
      content: "''",
      display: 'block',
      position: 'absolute',
      left: '-150px',
      top: '0',
      height: '100%',
      width: '150px',
      background: 'linear-gradient(to right, transparent 0%, #f3f3f3 50%, transparent 100%)',
      animation: '$load 1s cubic-bezier(0.4, 0.0, 0.2, 1) infinite',
    },
  },
  routingModal: {
    display: 'grid',
    gridTemplateRows: 'repeat(3, 1fr)',
    width: '90%',
    height: '120px',
    filter: 'drop-shadow(0px 20px 56px rgba(0, 0, 0, 0.29))',
    borderRadius: '8px',
  },
  searchContainer: {
    margin: '32px 0 24px 0',
  },
  dealSection: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background: theme.colors.white[100],
    height: '68px',
    borderRadius: '8px',
    [theme.breakpoints.down(phone)]: {
      height: '90px',
    },
  },
  smallBox: {
    height: '88px',
    width: '100%',
    borderRadius: '8px',
    boxShadow: 'none !important',
    padding: '16px 24px',
  },
  toast: {
    width: '344px',
    height: '56px',
    background: theme.colors.primary[25],
    boxShadow: '0px 6px 12px rgba(0, 0, 0, 0.11)',
    borderRadius: '8px',
    '& .Toastify__close-button > svg': {
      fill: 'currentColor',
      height: '50px',
      width: '20px',
    },
    '& .Toastify__close-button--default': {
      opacity: '1.0',
    },
  },
  toastBody: {
    fontWeight: 400,
    fontSize: '16px',
    color: theme.colors.gray[700],
  },
  tabsContainer: {
    [theme.breakpoints.down(phone)]: {
      overflowX: 'scroll',
      display: 'block',
    },
  },
  textBottom: {
    color: theme.colors.gray[500],
  },
  textFieldRoot: {
    width: '100%',
    '& .MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline': {
      borderColor: theme.colors.primary[500],
    },
  },
  textTop: {
    color: theme.colors.black[50],
  },
  viewButton: {
    fontSize: '16px',
    textTransform: 'none',
    padding: '1px 15px',
    fontWeight: 500,
    border: `1px solid ${theme.colors.gray[500]}`,
    marginLeft: '8px',
    height: '32px',
    color: theme.colors.gray[500],
    boxSizing: 'border-box',
    transition: '0s',
    '& svg': {
      marginRight: '8px',
    },
    '&:hover': {
      backgroundColor: theme.colors.primary[50],
      border: `1px solid ${theme.colors.gray[300]}`,
      outline: 'none',
    },
    '&:focus': {
      outline: 'none',
    },
  },
  viewButtonContainer: {
    // Need this to avoid movement when selecting buttons
    display: 'flex',
    justifyContent: 'center',
  },
  viewButtonSelected: {
    border: `2px solid ${theme.colors.primary[500]}`,
    color: theme.palette.primary.main,
    backgroundColor: theme.colors.primary[50],
    transition: '0s',
    '&:hover, &:focus': {
      border: `2px solid ${theme.colors.primary[500]}`,
    },
  },
  '@keyframes load': {
    from: { left: '-150px' },
    to: { left: '100%' },
  },
});

export default styles;
