import { makeStyles } from '@material-ui/core/styles';

const styles = makeStyles((theme) => ({
  assocOption: {
    cursor: 'pointer',
  },
  container: {
    display: 'flex',
    justifyContent: 'space-between',
    width: '100%',
    height: '85%',
    margin: '0',
    padding: '1rem 0',
    [theme.breakpoints.down(960)]: {
      flexDirection: 'column',
      overflowY: 'scroll',
    },
  },
  investorAmount: {
    padding: '0px 10px',
    margin: '0px 10px',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: "'Roboto'",
    fontWeight: 400,
  },
  investorItem: {
    display: 'flex',
    height: '3rem',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.colors.white[100],
    margin: '5px 0',
    borderRadius: '7.5px',
  },
  investorLabel: {
    height: '100%',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    fontFamily: "'Roboto'",
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '18px',
    color: theme.colors.black[50],
    padding: '0',
    margin: '0',
    textOverflow: ['ellipsis', 'ellipsis'],
    width: '75%',
    overflowX: 'scroll',
    whiteSpace: 'nowrap',
  },
  investorList: {
    listStyle: 'none',
    padding: '0',
    overflowY: 'scroll',
    height: '80%',
    borderRadius: '5px',
  },
  investors: {
    width: '49%',
    height: '100%',
    overflow: 'hidden',
    padding: '1rem',
    background: theme.colors.primary[25],
    borderRadius: '10px',
    '& button': {
      color: `${theme.colors.black[50]}80`,
      fontSize: '11px',
      fontFamily: "'Roboto'",
      padding: ['0', '5px'],
      outline: 'none',
      width: 'max-content',
    },
    [theme.breakpoints.down(960)]: {
      width: '100%',
    },
  },
  message: {
    width: '49%',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    padding: '1rem',
    background: theme.colors.primary[25],
    '& img': {
      width: '95%',
      overflow: 'hidden',
      objectFit: 'cover',
    },
    [theme.breakpoints.down(960)]: {
      width: '100%',
      height: '100%',
    },
  },
  sendButton: {
    background: theme.colors.black[50],
    color: theme.colors.white[100],
    width: '100%',
    textTransform: 'none',
    margin: '16px 0px',
  },
  SendWireReminder: {
    width: '100%',
    height: '75vh',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
  },
  title: {
    color: theme.colors.black[50],
    fontSize: '18px',
    fontWeight: 400,
  },
}));

export default styles;
