# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
#
# https://raw.githubusercontent.com/actions/starter-workflows/main/ci/node.js.yml
# https://github.com/actions/setup-node

name: Run Tests Node CI

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - '**' # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NODE_ENV: development
      REACT_APP_AUTH0_DOMAIN: ${{ secrets.REACT_APP_AUTH0_DOMAIN }}
      REACT_APP_AUTH0_KEY: ${{ secrets.REACT_APP_AUTH0_KEY }}
      REACT_APP_AUTH0_AUDIENCE: ${{ secrets.REACT_APP_AUTH0_AUDIENCE }}
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      REACT_APP_URL: ${{ secrets.REACT_APP_URL }}
      REACT_APP_VERIFY_INVESTOR_URL: ${{ secrets.REACT_APP_VERIFY_INVESTOR_URL }}
      REACT_APP_VERIFY_INVESTOR_HOST_TOKEN: ${{ secrets.REACT_APP_VERIFY_INVESTOR_HOST_TOKEN }}
      REACT_APP_AIRTABLE_API_KEY: ${{ secrets.REACT_APP_AIRTABLE_API_KEY }}
      REACT_APP_GOOGLE_MAP_API: ${{ secrets.REACT_APP_GOOGLE_MAP_API }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    strategy:
      matrix:
        node-version: [14.x, 16.x] #https://vercel.com/docs/runtimes
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        # https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test
