name: Build
on:
  push:
    branches: [master, staging]

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: ECR Setup
        id: setup-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Image
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          ECR_REGISTRY: ${{ steps.setup-ecr.outputs.registry }}
          SHA_IMAGE_TAG: ${{ github.sha }}
        run: |
          chmod +x ./.github/scripts/build.sh
          ./.github/scripts/build.sh
        shell: bash
